#设置端口号
server:
  port: 1234
#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/air_booking?useUnicode=true&characterEncoding=utf-8&&serverTimezone=Asia/Shanghai
    username: root
    password: root
#mybatis-plus 扫描配置
mybatis:
  type-aliases-package: com.air.airbooking.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#日志输出
logging:
  level:
    com.air.airbooking.mapper: debug